//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.28 at 11:16:09 AM EDT 
//


package edu.purdue.cybercenter.dm.xml.vocabulary;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.purdue.cybercenter.dm.xml.vocabulary package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.purdue.cybercenter.dm.xml.vocabulary
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Vocabulary }
     * 
     */
    public Vocabulary createVocabulary() {
        return new Vocabulary();
    }

    /**
     * Create an instance of {@link ValidationType }
     * 
     */
    public ValidationType createValidationType() {
        return new ValidationType();
    }

    /**
     * Create an instance of {@link Vocabulary.InheritedFrom }
     * 
     */
    public Vocabulary.InheritedFrom createVocabularyInheritedFrom() {
        return new Vocabulary.InheritedFrom();
    }

    /**
     * Create an instance of {@link AttachTo }
     * 
     */
    public AttachTo createAttachTo() {
        return new AttachTo();
    }

    /**
     * Create an instance of {@link Vocabulary.Contributors }
     * 
     */
    public Vocabulary.Contributors createVocabularyContributors() {
        return new Vocabulary.Contributors();
    }

    /**
     * Create an instance of {@link Vocabulary.Terms }
     * 
     */
    public Vocabulary.Terms createVocabularyTerms() {
        return new Vocabulary.Terms();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Term }
     * 
     */
    public Term createTerm() {
        return new Term();
    }

    /**
     * Create an instance of {@link ValidationType.Validator }
     * 
     */
    public ValidationType.Validator createValidationTypeValidator() {
        return new ValidationType.Validator();
    }

    /**
     * Create an instance of {@link Vocabulary.InheritedFrom.VocabularyRef }
     * 
     */
    public Vocabulary.InheritedFrom.VocabularyRef createVocabularyInheritedFromVocabularyRef() {
        return new Vocabulary.InheritedFrom.VocabularyRef();
    }

}
