//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.28 at 11:16:09 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cyber.purdue.edu/cris/schemas/vocabulary/1.0.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.purdue.cybercenter.dm.xml.vocabulary;
